### ISSUE TITLE
Migrate to GitLab?

### ISSUE THREAD

**Issue by PatchMixolydic** [vyletbunni/rttim#11]
Problem:
Microsoft acquired GitHub. Will RTTIM migrate to GitLab due to this?

Crash details:
Crash Bandicoot is a franchise of platform video games. The series was created by Andy Gavin and Jason Rubin during their tenure at Naughty Dog for Universal Interactive Studios and Sony Computer Entertainment; the series was originally exclusive to the PlayStation family of video game consoles. The series has appeared on multiple platforms and gone through various developers and spans numerous genres. The series comprises eighteen games and shipped over 50 million copies worldwide.

Log file:
```
AssertionError: switch to gitlab you nonce
```

Questions: 
- Will RTTIM migrate to GitLab due to this?
- how do i lan

**Comment by vyletbunni** [comment]
as long as 1) microsoft doesnt put a paywall up for public repos, 2) microsoft isnt making stupid storage limits, and 3) github isnt shutting down, im not moving rttim to another service

**Comment by PatchMixolydic** [comment]
K
