### ISSUE TITLE
No attribute of Native Ratio

### ISSUE THREAD

**Issue by TheMultiMan** [vyletbunni/rttim#2]
Game starts for one second and quits. The client gives me the error "AttributeError: ToonBase instance has no attribute 'nativeRatio"

Full log:
![image](https://user-images.githubusercontent.com/32345653/30942059-3a29b254-a3ae-11e7-8505-600f6dc6f897.png)

**Comment by dotthefox** [comment]
yee that happened to me too xd

**Comment by vyletbunni** [comment]
fixed in latest commit
